"""
Batch 4 bulk-register: parses Student-ID-3D-post-unreal-unity.xlsx
(4 sheets, single ID column, no names) and generates INSERT statements
for public.students with name = NULL.

Usage:
    python bulk_register_batch4.py <excel-file> [output.sql]
"""
import sys
import openpyxl

# Sheet name -> courses.code
SHEET_TO_COURSE_CODE = {
    "3D": "3D-ANIM",              # "3dani-k4-01" -- "ani" = Animation
    "Post-production": "POST-PROD",
    "Unity": "UNITY",
    "Unreal": "UNREAL",
}


def sql_escape(value: str) -> str:
    return value.replace("'", "''")


def main():
    if len(sys.argv) < 2:
        print("Usage: python bulk_register_batch4.py <excel-file> [output.sql]")
        sys.exit(1)

    excel_path = sys.argv[1]
    out_path = sys.argv[2] if len(sys.argv) > 2 else "bulk_register_batch4.sql"

    wb = openpyxl.load_workbook(excel_path, data_only=True)

    all_inserts = []
    summary = []
    warnings = []

    for sheet_name, course_code in SHEET_TO_COURSE_CODE.items():
        if sheet_name not in wb.sheetnames:
            warnings.append(f"Sheet '{sheet_name}' Excel me nahi mili -- skip.")
            continue

        ws = wb[sheet_name]
        seen = set()
        count = 0
        for r in range(2, ws.max_row + 1):  # row 1 = header
            raw = ws.cell(row=r, column=1).value
            if raw is None:
                continue
            roll_number = str(raw).strip()
            if not roll_number:
                continue
            if roll_number in seen:
                warnings.append(f"[{sheet_name}] Duplicate ID '{roll_number}' at row {r} -- skip.")
                continue
            seen.add(roll_number)
            count += 1

            all_inserts.append(
                "insert into public.students (roll_number, name, course_id) values "
                f"('{sql_escape(roll_number)}', NULL, "
                f"(select id from public.courses where code='{course_code}'));"
            )

        summary.append(f"  {sheet_name} -> {course_code}: {count} students")

    with open(out_path, "w", encoding="utf-8") as f:
        f.write("-- Auto-generated by scripts/bulk_register_batch4.py\n")
        f.write(f"-- Source: {excel_path}\n")
        f.write(f"-- Total students: {len(all_inserts)}\n\n")
        for stmt in all_inserts:
            f.write(stmt + "\n")

    print(f"Generated {len(all_inserts)} INSERT statements -> {out_path}")
    print("\nPer-course breakdown:")
    for line in summary:
        print(line)
    if warnings:
        print("\nWarnings:")
        for w in warnings:
            print(" -", w)


if __name__ == "__main__":
    main()
