"""
Bulk-register students from an attendance-register Excel file into
Supabase's `public.students` table.

Reads each sheet (one per course), auto-detects the data rows (a row
counts as a student row when column A is numeric and column B is a
non-empty name -- this is robust to each sheet having its header at a
different row, which this file's sheets do), and writes a single .sql
file with INSERT statements matching the ACTUAL live `students` schema:
    students(id uuid pk, roll_number text unique, name text,
             course_id uuid fk -> courses.id, face_encoding, created_at)

roll_number format: {COURSE_CODE}-{S.No}  (e.g. UNITY-1, PRE-PROD-5)
This keeps IDs human-readable and guarantees uniqueness across sheets
without needing a global counter, since each course has its own prefix.

Usage:
    python bulk_register_students.py <path-to-excel-file> [output.sql]
"""
import sys
import re
import openpyxl

# Excel sheet name -> courses.code (must already exist in the DB)
SHEET_TO_COURSE_CODE = {
    "Unity 3D": "UNITY",
    "Pre Production": "PRE-PROD",
    "Unreal Engine": "UNREAL",
    "Production": "PRODUCTION",
}


def clean_name(raw):
    """Trim + collapse internal whitespace/newlines."""
    if raw is None:
        return ""
    return re.sub(r"\s+", " ", str(raw)).strip()


def extract_students(ws):
    """
    Walk every row; a row is a student row when column A is a number
    (int/float, or a numeric string) and column B is a non-empty name.
    Returns list of (s_no:int, name:str) in row order.
    """
    rows = []
    for r in range(1, ws.max_row + 1):
        a = ws.cell(row=r, column=1).value
        b = ws.cell(row=r, column=2).value
        is_num = isinstance(a, (int, float)) or (isinstance(a, str) and a.strip().isdigit())
        name = clean_name(b)
        if is_num and name:
            rows.append((int(a), name))
    return rows


def sql_escape(value: str) -> str:
    return value.replace("'", "''")


def main():
    if len(sys.argv) < 2:
        print("Usage: python bulk_register_students.py <excel-file> [output.sql]")
        sys.exit(1)

    excel_path = sys.argv[1]
    out_path = sys.argv[2] if len(sys.argv) > 2 else "bulk_register_students.sql"

    wb = openpyxl.load_workbook(excel_path, data_only=True)

    all_inserts = []
    summary = []
    warnings = []

    for sheet_name, course_code in SHEET_TO_COURSE_CODE.items():
        if sheet_name not in wb.sheetnames:
            warnings.append(f"Sheet '{sheet_name}' Excel file me nahi mili -- skip kar diya.")
            continue

        ws = wb[sheet_name]
        students = extract_students(ws)

        seen_sno = {}
        for s_no, name in students:
            if s_no in seen_sno:
                warnings.append(
                    f"[{sheet_name}] Duplicate S.No {s_no} -- rows with names "
                    f"'{seen_sno[s_no]}' and '{name}' both map to roll_number "
                    f"'{course_code}-{s_no}'. Dusri wali skip ki."
                )
                continue
            seen_sno[s_no] = name

            roll_number = f"{course_code}-{s_no}"
            all_inserts.append(
                "insert into public.students (roll_number, name, course_id) values "
                f"('{sql_escape(roll_number)}', '{sql_escape(name)}', "
                f"(select id from public.courses where code='{course_code}'));"
            )

        summary.append(f"  {sheet_name} -> {course_code}: {len(seen_sno)} students")

    with open(out_path, "w", encoding="utf-8") as f:
        f.write("-- Auto-generated by scripts/bulk_register_students.py\n")
        f.write(f"-- Source: {excel_path}\n")
        f.write(f"-- Total students: {len(all_inserts)}\n\n")
        for stmt in all_inserts:
            f.write(stmt + "\n")

    print(f"Generated {len(all_inserts)} INSERT statements -> {out_path}")
    print("\nPer-course breakdown:")
    for line in summary:
        print(line)
    if warnings:
        print("\nWarnings:")
        for w in warnings:
            print(" -", w)


if __name__ == "__main__":
    main()
